chore: debug watcher build

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -228,8 +228,9 @@ jobs:
           vvar_tag=$(cat full_version_output | jq -r ".dockerTagSafeVersion")
           # build and push docker image
           cd reliza-watcher
-          docker build . -t relizaio/reliza-watcher:$vvar_tag -t relizaio/reliza-watcher:latest \
-           --build-arg VERSION=$vvar --build-arg CI_ENV=github$GITHUB_SHA --build-arg GIT_COMMIT=$GITHUB_SHA --build-arg GIT_BRANCH=$GITHUB_REF
+          docker build . -t relizaio/reliza-watcher:$vvar_tag -t relizaio/reliza-watcher:latest --build-arg VERSION=$vvar --build-arg CI_ENV=github$GITHUB_SHA --build-arg GIT_COMMIT=$GITHUB_SHA --build-arg GIT_BRANCH=$GITHUB_REF > build.log 2>&1 || echo "build failed"
+          cat build.log
+          exit 1
           echo "debug: after build before push"
           docker_sha_256=$(docker push relizaio/reliza-watcher:$vvar_tag | grep sha256 | cut -f 3 -d ' ')
           echo "new sha 256 $docker_sha_256"
