chore: debug on reliza watcher build

diff --git a/.github/workflows/dockerimage.yml b/.github/workflows/dockerimage.yml
--- a/.github/workflows/dockerimage.yml
+++ b/.github/workflows/dockerimage.yml
@@ -213,6 +213,7 @@ jobs:
           last_commit=$(docker run --rm relizaio/reliza-cli getlatestrelease \
             -i ${{ secrets.RELIZA_KUBECTL_RELIZA_CLIENT_API_ID }} -k ${{ secrets.RELIZA_KUBECTL_RELIZA_CLIENT_API_KEY }} \
             --branch $GITHUB_REF | jq -r ".sourceCodeEntryDetails.commit")
+          echo "last commit = $last_commit"
           if [ ! -z "$last_commit" ]
           then
             echo -n "--commits $(git log $last_commit..$GITHUB_SHA --date=iso-strict --pretty='%H|||%ad|||%s' | base64 -w 0) " > commit_list
@@ -220,7 +221,7 @@ jobs:
           # obtain version
           docker run --rm relizaio/reliza-cli getversion \
             -i ${{ secrets.RELIZA_KUBECTL_RELIZA_CLIENT_API_ID }} -k ${{ secrets.RELIZA_KUBECTL_RELIZA_CLIENT_API_KEY }} -b $GITHUB_REF
-            --commit $GITHUB_SHA --commitmessage \"$(git log -1 --pretty='%s')\" $(cat commit_list) > full_version_output 2>&1
+            --commit $GITHUB_SHA --commitmessage \"$(git log -1 --pretty='%s')\" $(cat commit_list) > full_version_output 2>&1 || echo "getting version failed"
           echo "Version response:"
           cat full_version_output
           # now construct actual version variable
@@ -228,9 +229,8 @@ jobs:
           vvar_tag=$(cat full_version_output | jq -r ".dockerTagSafeVersion")
           # build and push docker image
           cd reliza-watcher
-          docker build . -t relizaio/reliza-watcher:$vvar_tag -t relizaio/reliza-watcher:latest --build-arg VERSION=$vvar --build-arg CI_ENV=github$GITHUB_SHA --build-arg GIT_COMMIT=$GITHUB_SHA --build-arg GIT_BRANCH=$GITHUB_REF > build.log 2>&1 || echo "build failed"
-          cat build.log
-          exit 1
+          docker build . -t relizaio/reliza-watcher:$vvar_tag -t relizaio/reliza-watcher:latest 
+           --build-arg VERSION=$vvar --build-arg CI_ENV=github$GITHUB_SHA --build-arg GIT_COMMIT=$GITHUB_SHA --build-arg GIT_BRANCH=$GITHUB_REF
           echo "debug: after build before push"
           docker_sha_256=$(docker push relizaio/reliza-watcher:$vvar_tag | grep sha256 | cut -f 3 -d ' ')
           echo "new sha 256 $docker_sha_256"
